language: python
python:
   - "3.5"
cache: pip

install:

  - pip install -r requirements.txt


script:
  - coverage run --source=app.api.v1 -m pytest  app/tests && coverage reportS
  - coveralls

after_success:
    - coveralls
